<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">generateBLOBCLOB</value>
  <array name="sig" type="value" depth="1">
    <value>[i] object:0:required recordCount</value>
    <value>[i] object:0:required blobSize</value>
    <value>[i] object:0:required clobSize</value>
    <value>[o] record:1:required inputs</value>
    <value>[o] - object:0:required BLOB_COL</value>
    <value>[o] - object:0:required CLOB_COL</value>
    <value>[o] - object:0:required INT_COL</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKSW50ZWdlciByZWNvcmRDb3VudCA9IChJbnRlZ2VyKUlEYXRhVXRpbC5nZXQocGlwZWxp
bmVDdXJzb3IsInJlY29yZENvdW50Iik7CkxvbmcgYmxvYlNpemUgPSAoTG9uZylJRGF0YVV0aWwu
Z2V0KHBpcGVsaW5lQ3Vyc29yLCJibG9iU2l6ZSIpOwpMb25nIGNsb2JTaXplID0gKExvbmcpSURh
dGFVdGlsLmdldChwaXBlbGluZUN1cnNvciwiY2xvYlNpemUiKTsKSW5wdXRTdHJlYW0gaW5wdXRT
dHJlYW07ClJlYWRlciByZWFkZXI7CnRyeQp7CglGaWxlIHRlbXBGaWxlID0gRmlsZS5jcmVhdGVU
ZW1wRmlsZSgiYmxvYiIsIi50bXAiKTsKCUZpbGVPdXRwdXRTdHJlYW0gZmlsZU91dHB1dFN0cmVh
bSA9IG5ldyBGaWxlT3V0cHV0U3RyZWFtKHRlbXBGaWxlKTsKCWludCBhcnJheVNpemUgPSAxMDI0
OwoJYnl0ZVtdIGIgPSBuZXcgYnl0ZVthcnJheVNpemVdOwoJZm9yIChpbnQgaSA9IDA7IGkgPCBi
Lmxlbmd0aDsgaSsrKQoJewoJCWJbaV0gPSAoYnl0ZSkoaSAlIDEyOCk7Cgl9Cglsb25nIGJ5dGVz
V3JpdHRlbiA9IDA7Cgl3aGlsZSAoYnl0ZXNXcml0dGVuIDwgYmxvYlNpemUubG9uZ1ZhbHVlKCkp
Cgl7CgkJaWYgKChibG9iU2l6ZS5sb25nVmFsdWUoKSAtIGJ5dGVzV3JpdHRlbikgPCBhcnJheVNp
emUpCgkJewoJCQlhcnJheVNpemUgPSAoaW50KShibG9iU2l6ZS5sb25nVmFsdWUoKSAtIGJ5dGVz
V3JpdHRlbik7CgkJfQkJCgkJZmlsZU91dHB1dFN0cmVhbS53cml0ZShiLCAwLCBhcnJheVNpemUp
OwoJCWJ5dGVzV3JpdHRlbiArPSBhcnJheVNpemU7Cgl9CglmaWxlT3V0cHV0U3RyZWFtLmNsb3Nl
KCk7CglpbnB1dFN0cmVhbSA9IG5ldyBGaWxlSW5wdXRTdHJlYW0odGVtcEZpbGUpOwp9CmNhdGNo
IChJT0V4Y2VwdGlvbiBlKQp7Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlKTsKfQp0cnkK
ewoJRmlsZSB0ZW1wRmlsZSA9IEZpbGUuY3JlYXRlVGVtcEZpbGUoImNsb2IiLCIudG1wIik7CglG
aWxlV3JpdGVyIGZpbGVXcml0ZXIgPSBuZXcgRmlsZVdyaXRlcih0ZW1wRmlsZSk7CglpbnQgYXJy
YXlTaXplID0gMTAyNDsKCWNoYXJbXSBjID0gbmV3IGNoYXJbYXJyYXlTaXplXTsKCWZvciAoaW50
IGkgPSAwOyBpIDwgYy5sZW5ndGg7IGkrKykKCXsKCQljW2ldID0gJ2MnOwoJfQoJbG9uZyBjaGFy
c1dyaXR0ZW4gPSAwOwoJd2hpbGUgKGNoYXJzV3JpdHRlbiA8IGNsb2JTaXplLmxvbmdWYWx1ZSgp
KQoJewoJCWlmICgoY2xvYlNpemUubG9uZ1ZhbHVlKCkgLSBjaGFyc1dyaXR0ZW4pIDwgYXJyYXlT
aXplKQoJCXsKCQkJYXJyYXlTaXplID0gKGludCkoY2xvYlNpemUubG9uZ1ZhbHVlKCkgLSBjaGFy
c1dyaXR0ZW4pOwoJCX0JCQoJCWZpbGVXcml0ZXIud3JpdGUoYywgMCwgYXJyYXlTaXplKTsKCQlj
aGFyc1dyaXR0ZW4gKz0gYXJyYXlTaXplOwoJfQoJZmlsZVdyaXRlci5jbG9zZSgpOwoJcmVhZGVy
ID0gbmV3IEZpbGVSZWFkZXIodGVtcEZpbGUpOwp9CmNhdGNoIChJT0V4Y2VwdGlvbiBlKQp7Cgl0
aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlKTsKfQovLyBJbml0aWFsaXplIHN0YXJ0CmludCBz
dGFydCA9IDE7CklEYXRhIFtdIFRfcm93ID0gbmV3IElEYXRhW3JlY29yZENvdW50LmludFZhbHVl
KCldOwpmb3IgKGludCBpID0gc3RhcnQ7IGkgPD0gcmVjb3JkQ291bnQuaW50VmFsdWUoKTsgaSsr
KQp7CQoJT2JqZWN0IG9yb3dbXVtdID0ge3siQkxPQl9DT0wiLCBpbnB1dFN0cmVhbX0sCgkJeyJD
TE9CX0NPTCIsIHJlYWRlcn0sCgkJeyJJTlRfQ09MIiwgbmV3IEJpZ0RlY2ltYWwoaSl9fTsKCVRf
cm93W2ktc3RhcnRdID0gKElEYXRhKW5ldyBWYWx1ZXMob3Jvdyk7Cn0KVmFsdWVzRW11bGF0b3Iu
cHV0KHBpcGVsaW5lLCJpbnB1dHMiLFRfcm93KTsKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOwo=
</value>
</Values>
