<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">loadConnectionProperties</value>
  <array name="sig" type="value" depth="1">
    <value>[o] field:0:required connectionAlias</value>
    <value>[o] field:0:required packageName</value>
    <value>[o] field:0:required adapterTypeName</value>
    <value>[o] field:0:required connectionFactoryType</value>
    <value>[o] field:0:required serverName</value>
    <value>[o] field:0:required siebelEnterprise</value>
    <value>[o] field:0:required objectManager</value>
    <value>[o] field:0:required language</value>
    <value>[o] field:0:required username</value>
    <value>[o] field:0:required password</value>
    <value>[o] field:0:required expireTimeout</value>
    <value>[o] field:0:required startupRetryCount</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRhdGFjdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3RyaW5nIGNv
bm5lY3Rpb25BbGlhcyA9ICJjb20ud2VibWV0aG9kcy5hZGFwdGVycy5qZGJjLmNvbm5lY3Rpb25z
Lm9yYWNsZTpDb25uZWN0aW9uIjsKU3RyaW5nIHBhY2thZ2VOYW1lID0gIkpEQkNSZWdyZXNzaW9u
IjsKU3RyaW5nIGFkYXB0ZXJUeXBlTmFtZSA9ICJKREJDQWRhcHRlciI7ClN0cmluZyBjb25uZWN0
aW9uRmFjdG9yeVR5cGUgPSAiY29tLndtLmFkYXB0ZXIud21qZGJjLmNvbm5lY3Rpb24uSkRCQ0Nv
bm5lY3Rpb25GYWN0b3J5IjsKU3RyaW5nIHRyYW5zYWN0aW9uVHlwZSA9ICIiOwpTdHJpbmcgZGF0
YXNvdXJjZUNsYXNzID0gIiI7ClN0cmluZyBzZXJ2ZXJOYW1lID0gIiI7ClN0cmluZyBkYXRhYmFz
ZU5hbWUgPSAiIjsKU3RyaW5nIHVzZXJuYW1lID0gIiI7ClN0cmluZyBwYXNzd29yZCA9ICIiOwpT
dHJpbmcgcG9ydE51bWJlciA9ICIiOwpTdHJpbmcgbmV0d29ya1Byb3RvY29sID0gIiI7ClN0cmlu
ZyBvdGhlclByb3BlcnRpZXMgPSAiIjsKdHJ5CnsKCVByb3BlcnRpZXMgcHJvcCA9IG5ldyBQcm9w
ZXJ0aWVzKCk7CglTdHJpbmcgcHJvcFBhdGggPSAicGFja2FnZXNcXEpEQkNSZWdyZXNzaW9uXFxj
b25maWdcXEpEQkNBdXRvbWF0aW9uLnByb3BlcnRpZXMiOwoJcHJvcC5sb2FkKG5ldyBGaWxlSW5w
dXRTdHJlYW0ocHJvcFBhdGgpKTsKICAgICAgICBpZihwcm9wLmdldCgiY29ubmVjdGlvbkFsaWFz
IikhPSBudWxsKQoJCWNvbm5lY3Rpb25BbGlhcyA9IChTdHJpbmcpcHJvcC5nZXQoImNvbm5lY3Rp
b25BbGlhcyIpOwogICAgICAgIGlmKHByb3AuZ2V0KCJhZGFwdGVyVHlwZU5hbWUiKSE9IG51bGwp
CgkJYWRhcHRlclR5cGVOYW1lID0gKFN0cmluZylwcm9wLmdldCgiYWRhcHRlclR5cGVOYW1lIik7
CiAgICAgICAgaWYocHJvcC5nZXQoInBhY2thZ2VOYW1lIikhPSBudWxsKQoJCXBhY2thZ2VOYW1l
ID0gKFN0cmluZylwcm9wLmdldCgicGFja2FnZU5hbWUiKTsKICAgICAgICBpZihwcm9wLmdldCgi
Y29ubmVjdGlvbkZhY3RvcnlUeXBlIikhPSBudWxsKQoJCWNvbm5lY3Rpb25GYWN0b3J5VHlwZSA9
IChTdHJpbmcpcHJvcC5nZXQoImNvbm5lY3Rpb25GYWN0b3J5VHlwZSIpOwogICAgICAgIGlmKHBy
b3AuZ2V0KCJ0cmFuc2FjdGlvblR5cGUiKSE9IG51bGwpCgkJdHJhbnNhY3Rpb25UeXBlID0gKFN0
cmluZylwcm9wLmdldCgidHJhbnNhY3Rpb25UeXBlIik7CglpZihwcm9wLmdldCgiZGF0YXNvdXJj
ZUNsYXNzIikhPSBudWxsKQoJCWRhdGFzb3VyY2VDbGFzcyA9IChTdHJpbmcpcHJvcC5nZXQoImRh
dGFzb3VyY2VDbGFzcyIpOwoJaWYocHJvcC5nZXQoInNlcnZlck5hbWUiKSE9IG51bGwpCgkJc2Vy
dmVyTmFtZSA9IChTdHJpbmcpcHJvcC5nZXQoInNlcnZlck5hbWUiKTsKICAgICAgICBpZihwcm9w
LmdldCgiZGF0YWJhc2VOYW1lIikhPSBudWxsKQoJCWRhdGFiYXNlTmFtZSA9IChTdHJpbmcpcHJv
cC5nZXQoImRhdGFiYXNlTmFtZSIpOwkgCglpZihwcm9wLmdldCgidXNlcm5hbWUiKSE9IG51bGwp
CgkJdXNlcm5hbWUgPSAoU3RyaW5nKXByb3AuZ2V0KCJ1c2VybmFtZSIpOwkgCglpZihwcm9wLmdl
dCgicGFzc3dvcmQiKSE9IG51bGwpCgkJcGFzc3dvcmQgPSAoU3RyaW5nKXByb3AuZ2V0KCJwYXNz
d29yZCIpOwkgCglpZihwcm9wLmdldCgicG9ydE51bWJlciIpIT0gbnVsbCkKCQlwb3J0TnVtYmVy
ID0gKFN0cmluZylwcm9wLmdldCgicG9ydE51bWJlciIpOwkgCglpZihwcm9wLmdldCgibmV0d29y
a1Byb3RvY29sIikhPSBudWxsKQoJCW5ldHdvcmtQcm90b2NvbCA9IChTdHJpbmcpcHJvcC5nZXQo
Im5ldHdvcmtQcm90b2NvbCIpOwkgCglpZihwcm9wLmdldCgib3RoZXJQcm9wZXJ0aWVzIikhPSBu
dWxsKQoJCW90aGVyUHJvcGVydGllcyA9IChTdHJpbmcpcHJvcC5nZXQoIm90aGVyUHJvcGVydGll
cyIpOwkgCn0KY2F0Y2goRXhjZXB0aW9uIGUpCnsKCS8vaWdub3JlIHRoZSBleGNlcHRpb24gYW5k
IGRlZmF1bHQgdGhlIHZhbHVlcwp9CmlkYXRhY3Vyc29yLmluc2VydEFmdGVyKCJjb25uZWN0aW9u
QWxpYXMiLCBjb25uZWN0aW9uQWxpYXMpOwppZGF0YWN1cnNvci5pbnNlcnRBZnRlcigicGFja2Fn
ZU5hbWUiLCBwYWNrYWdlTmFtZSk7CmlkYXRhY3Vyc29yLmluc2VydEFmdGVyKCJhZGFwdGVyVHlw
ZU5hbWUiLCBhZGFwdGVyVHlwZU5hbWUpOwppZGF0YWN1cnNvci5pbnNlcnRBZnRlcigiY29ubmVj
dGlvbkZhY3RvcnlUeXBlIiwgY29ubmVjdGlvbkZhY3RvcnlUeXBlKTsKaWRhdGFjdXJzb3IuaW5z
ZXJ0QWZ0ZXIoInRyYW5zYWN0aW9uVHlwZSIsIHRyYW5zYWN0aW9uVHlwZSk7CmlkYXRhY3Vyc29y
Lmluc2VydEFmdGVyKCJkYXRhc291cmNlQ2xhc3MiLCBkYXRhc291cmNlQ2xhc3MpOwppZGF0YWN1
cnNvci5pbnNlcnRBZnRlcigic2VydmVyTmFtZSIsIHNlcnZlck5hbWUpOwppZGF0YWN1cnNvci5p
bnNlcnRBZnRlcigiZGF0YWJhc2VOYW1lIiwgZGF0YWJhc2VOYW1lKTsKaWRhdGFjdXJzb3IuaW5z
ZXJ0QWZ0ZXIoInVzZXJuYW1lIiwgdXNlcm5hbWUpOwppZGF0YWN1cnNvci5pbnNlcnRBZnRlcigi
cGFzc3dvcmQiLCBwYXNzd29yZCk7CmlkYXRhY3Vyc29yLmluc2VydEFmdGVyKCJwb3J0TnVtYmVy
IiwgcG9ydE51bWJlcik7CmlkYXRhY3Vyc29yLmluc2VydEFmdGVyKCJuZXR3b3JrUHJvdG9jb2wi
LCBuZXR3b3JrUHJvdG9jb2wpOwppZGF0YWN1cnNvci5pbnNlcnRBZnRlcigib3RoZXJQcm9wZXJ0
aWVzIiwgb3RoZXJQcm9wZXJ0aWVzKTsKaWRhdGFjdXJzb3IuZGVzdHJveSgpOwo=</value>
</Values>
