<?xml version="1.0" encoding="UTF-8"?><action xmlns="http://com.softwareag.rules/action" version="10.1.0.0.172">
    <comment/>
    <type>Service Action</type>
    <implementation>
        <imports/>
        <function>(deffunction actionAction2Call (?dataType ?outputElement ?INPUTIDATA)(bind ?OUTPUTIDATA (defaultServiceCall "rulesDeployerTests" "flowservice1" ?INPUTIDATA)) (DataModelHelperUtils.createOutputObjectFromIData ?dataType ?outputElement ?OUTPUTIDATA))</function>
        <call>(actionAction2Call ?OUTPUT_SIGNATURE (getActionIDataInput ?INPUT_SIGNATURE))</call>
    </implementation>
    <input/>
    <output/>
    <dependencies>
        <dependsOn>IS:rulesDeployerTests.flowservice1</dependsOn>
    </dependencies>
    <properties>
        <property>
            <propertyName>property.action.name</propertyName>
            <propertyValue>Action2</propertyValue>
        </property>
        <property>
            <propertyName>property.action.call</propertyName>
            <propertyValue>(actionAction2Call ?OUTPUT_SIGNATURE (getActionIDataInput ?INPUT_SIGNATURE))</propertyValue>
        </property>
        <property>
            <propertyName>ISServiceName</propertyName>
            <propertyValue>flowservice1</propertyValue>
        </property>
        <property>
            <propertyName>ISServiceNamespace</propertyName>
            <propertyValue>rulesDeployerTests</propertyValue>
        </property>
        <property>
            <propertyName>property.action.run.once</propertyName>
            <propertyValue>false</propertyValue>
        </property>
        <property>
            <propertyName>property.action.function</propertyName>
            <propertyValue>(deffunction actionAction2Call (?dataType ?outputElement ?INPUTIDATA)(bind ?OUTPUTIDATA (defaultServiceCall "rulesDeployerTests" "flowservice1" ?INPUTIDATA)) (DataModelHelperUtils.createOutputObjectFromIData ?dataType ?outputElement ?OUTPUTIDATA))</propertyValue>
        </property>
    </properties>
</action>