// generated by Glue 8.0 Fix 1 build null (wsdl2java) on Tue Dec 14 14:08:38 PST 2010

package com.webmethods.caf.is.wsclient.wmwebsrv.wsd.addintswsdl;

public class addIntsOutput implements java.io.Serializable
  {
  private java.lang.String value;

  public java.lang.String getValue()
    {
    return value;
    }

  public void setValue( java.lang.String value )
    {
    this.value = value;
    }
  }
