// generated by Glue 8.0 Fix 1 build null (wsdl2java) on Tue Dec 14 14:08:38 PST 2010

package com.webmethods.caf.is.wsclient.wmwebsrv.wsd.addintswsdl;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class addIntsWSDLHelper
  {
  public static IaddInts_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Projects/automation/test/Data/trunk/DeployerAssets/DeployTestTaskApp/src/com/webmethods/caf/is/wsclient/wmwebsrv/wsd/addintswsdl/addIntsWSDL.wsdl" );
    }

  public static IaddInts_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IaddInts_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IaddInts_PortType) Registry.bind( url, IaddInts_PortType.class, context );
    }
  }
