// generated by Glue 8.0 Fix 1 build null (wsdl2java) on Tue Dec 14 14:08:38 PST 2010

package com.webmethods.caf.is.wsclient.wmwebsrv.wsd.addintswsdl;

public class addIntsInput implements java.io.Serializable
  {
  private java.lang.String num1;
  private java.lang.String num2;

  public java.lang.String getNum1()
    {
    return num1;
    }

  public void setNum1( java.lang.String value )
    {
    this.num1 = value;
    }

  public java.lang.String getNum2()
    {
    return num2;
    }

  public void setNum2( java.lang.String value )
    {
    this.num2 = value;
    }
  }
