// generated by Glue 8.0 Fix 1 build null (wsdl2java) on Tue Dec 14 14:08:38 PST 2010

package com.webmethods.caf.is.wsclient.wmwebsrv.wsd.addintswsdl;

public interface IaddInts_PortType
  {
  public com.webmethods.caf.is.wsclient.wmwebsrv.wsd.addintswsdl.addIntsOutput addInts( com.webmethods.caf.is.wsclient.wmwebsrv.wsd.addintswsdl.addIntsInput addIntsInput );
  }
